@startuml
rectangle "As a customer, I want to browse the\ncatalog and view different furniture\ncategories and products." as US1
rectangle "As a customer, I want to search for\nspecific furniture items by keywords\nor filters." as US2
rectangle "As a customer, I want to view detailed\ninformation about a specific furniture\nproduct, including images, description,\nspecifications, and customer reviews." as US3
rectangle "As a customer, I want to add furniture\nitems to my cart and proceed to checkout." as US4
rectangle "As a customer, I want to create an\naccount and save my favorite furniture\nitems for future reference." as US5

US1 -- US2
US2 -- US3
US2 -- US4
@enduml
